version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: projeto3
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@projeto3.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

  projeto3:
    build:
      context: .
      dockerfile: dockerfile
    container_name: projeto3
    working_dir: /app
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/projeto3
      PYTHONUNBUFFERED: '1'
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
  grafana_data:
